(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var l,m="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b};function n(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var d=a[b];if(d&&d.Math==Math)return d}throw Error("Cannot find global object");}var r=n(this),u;
if("function"==typeof Object.setPrototypeOf)u=Object.setPrototypeOf;else{var v;a:{var w={a:!0},x={};try{x.__proto__=w;v=x.a;break a}catch(a){}v=!1}u=v?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var y=u;
function z(a,b){a.prototype=m(b.prototype);a.prototype.constructor=a;if(y)y(a,b);else for(var d in b)if("prototype"!=d)if(Object.defineProperties){var f=Object.getOwnPropertyDescriptor(b,d);f&&Object.defineProperty(a,d,f)}else a[d]=b[d];a.O=b.prototype}var C=this||self;function D(a){a=1-a;return 1-a*a*a};var E=/[^\d]+$/;function F(a,b,d,f){if(!a.hasAttribute(b))return d;a=a.getAttribute(b);isNaN(parseFloat(a))?f=d:(d=parseFloat(a),(a=(a=a.match(E))&&a[0]||null)&&(a=a.trim()),b=d,"%"==a&&(b=Number((d/100*f).toFixed(2))),f=b);return f};function G(a,b,d){var f=F(a,"xenter",0,b),e=a.hasAttribute("xmiddle")?F(a,"xmiddle",0,b):void 0,c=F(a,"xexit",0,b),h=F(a,"yenter",0,d),k=a.hasAttribute("ymiddle")?F(a,"ymiddle",0,d):void 0,g=F(a,"yexit",0,d),p=H(a,"opacityenter"),q=H(a,"opacitymiddle"),A=H(a,"opacityexit"),B=a.hasAttribute("fixed"),S=a.getAttribute("assettype")||"",T=a.getAttribute("source")||"",U=a.getAttribute("easing")||"linear";b=F(a,"width",b,b);d=F(a,"height",d,d);var V=a.hasAttribute("yawenter")?parseInt(a.getAttribute("yawenter"),
10):void 0,W=a.hasAttribute("yawmiddle")?parseInt(a.getAttribute("yawmiddle"),10):void 0,X=a.hasAttribute("yawexit")?parseInt(a.getAttribute("yawexit"),10):void 0,Y=a.getAttribute("exit-url")||void 0,t=[];t.push({opacity:p,x:f,y:h,m:V});void 0!==e&&void 0!==k&&t.push({opacity:q,x:e,y:k,m:W});t.push({opacity:A,x:c,y:g,m:X});return{J:S,i:t,easing:U,element:a,F:Y,fixed:B,height:d,source:T,width:b}}
function I(a,b,d,f,e,c){e=void 0===e?0:e;c=void 0===c?1:c;if(f<=e)return a;if(f>=c)return b;switch(d){case "ease-in":d=f*f*f;e*=e*e;c*=c*c;break;case "ease-in-out":d=3*f*f-2*f*f*f;e=3*e*e-2*e*e*e;c=3*c*c-2*c*c*c;break;case "ease-out":d=D(f);e=D(e);c=D(c);break;default:d=f}return 1/(c-e)*(b-a)*(d-e)+a}function H(a,b){if(!a.hasAttribute(b))return 1;a=a.getAttribute(b);a=parseFloat(a);return isNaN(a)?1:0>a?0:1<a?1:a};function J(a,b,d){a=parseFloat(a.getAttribute(b));isFinite(a)||(a=d);return a};function K(a,b){this.h=b===L?a:""}K.prototype.toString=function(){return this.h.toString()};K.prototype.l=!0;K.prototype.j=function(){return this.h.toString()};var M=/^(?:(?:https?|mailto|ftp):|[^:/?#]*(?:[/?#]|$))/i,L={};function N(a){return"gwd-page"==a.tagName.toLowerCase()||"gwd-page"==a.getAttribute("is")}function aa(a){if(N(a))return a;for(;a&&9!=a.nodeType;)if((a=a.parentElement)&&N(a))return a;return null};function O(a,b,d){d=void 0===d?null:d;var f=document.createEvent("CustomEvent");f.initCustomEvent(a,!0,!0,d);b.dispatchEvent(f);return f};var ba=[];function P(){var a=HTMLElement.call(this)||this;a.u=[];a.B=null;a.l=null;a.j=[0,1];a.h=[];a.v=a.K.bind(a);a.G=!1;a.C=!1;a.D=a.N.bind(a);a.A=0;a.I=a.M.bind(a);a.H=a.L.bind(a);a.o=null;return a}z(P,HTMLElement);l=P.prototype;
l.connectedCallback=function(){this.ownerDocument.addEventListener("hostpagescroll",this.D);window.Enabler&&(Enabler.addEventListener(studio.events.StudioEvent.FULLSCREEN_EXPAND_FINISH,this.I),Enabler.addEventListener(studio.events.StudioEvent.FULLSCREEN_COLLAPSE_FINISH,this.H));if(!this.gwdIsLoaded()){var a=aa(this);a?a.gwdIsLoaded()&&this.gwdLoad():this.gwdLoad()}};
l.disconnectedCallback=function(){this.ownerDocument.removeEventListener("hostpagescroll",this.D);window.Enabler&&(Enabler.removeEventListener(studio.events.StudioEvent.FULLSCREEN_EXPAND_FINISH,this.I),Enabler.removeEventListener(studio.events.StudioEvent.FULLSCREEN_COLLAPSE_FINISH,this.H));this.removeEventListener("ready",this.v,!1)};
l.gwdLoad=function(){if(!this.gwdIsLoaded()){this.h.length=0;this.initializeParallax(!0);for(var a=this.h.length-1;0<=a;a--)this.h[a].gwdLoad();this.h=this.h.filter(function(b){return!b.gwdIsLoaded()});0==this.h.length?Q(this):this.addEventListener("ready",this.v,!1)}};l.gwdIsLoaded=function(){return this.G&&0==this.h.length};l.K=function(a){a=this.h.indexOf(a.target);0<=a&&(this.h.splice(a,1),0==this.h.length&&(Q(this),this.removeEventListener("ready",this.v,!1)))};
function Q(a){a.C||O("ready",a);a.C=!0;a.o&&(R(a,a.o.creativeFramePercentY,a.o.windowHeight+a.l),a.o=null)}
l.initializeParallax=function(a){var b=this;this.style.overflow="hidden";this.u.length=0;this.B=this.clientWidth;this.l=this.clientHeight;this.j=ca(this);for(var d=this.ownerDocument,f={},e=0;e<this.children.length;f={s:f.s},e++)if(!this.children[e].hasAttribute("data-gwd-csd-ghost-id")){var c=G(this.children[e],this.B,this.l);this.u.push(c);c.element.style.position="absolute";c.element.style.left="0px";c.element.style.top="0px";c.element.style.width=c.width+"px";c.element.style.height=c.height+"px";
c.element.style.transform="translate("+c.i[0].x+"px, "+c.i[0].y+"px)";c.element.style.opacity=c.i[0].opacity+"";void 0!=c.i[0].m&&c.element.setTargetYaw(c.i[0].m);if(a){if("image"==c.J&&c.source){for(;c.element.firstChild;)c.element.removeChild(c.element.firstChild);var h=d.createElement("gwd-image");h.style.width="100%";h.style.height="100%";h.setAttribute("source",c.source);this.h.push(h);c.element.appendChild(h)}else c.element.gwdLoad&&this.h.push(c.element);c.F&&(f.s=c.F,c.element.addEventListener("click",
function(k){return function(){if(!O("layerclickexit",b,{url:k.s}).detail.handled){var g=k.s;g instanceof K||g instanceof K||(g="object"==typeof g&&g.l?g.j():String(g),M.test(g)||(g="about:invalid#zClosurez"),g=new K(g,L));C.open(g instanceof K&&g.constructor===K?g.h:"type_error:SafeUrl","")}}}(f)))}}this.G=!0};l.N=function(a){a=a.detail;this.A=a.creativeFramePercentY;this.gwdIsLoaded()?R(this,a.creativeFramePercentY,a.windowHeight+this.l):this.o=a};
function R(a,b,d){for(var f=0;f<a.u.length;f++){var e=a.u[f],c=void 0,h=void 0;c=e.i.length-1;var k=a.j[0],g=a.j[a.j.length-1],p=e.i[0],q=e.i[e.i.length-1];if(e.i.length===a.j.length)for(h=0;h<c;h++)if(a.j[h]<=b&&b<=a.j[h+1]){k=a.j[h];g=a.j[h+1];p=e.i[h];q=e.i[h+1];break}e.fixed?(c=e.i[0].x,h=e.i[0].y+b*d):(c=I(p.x,q.x,e.easing,b,k,g),h=I(p.y,q.y,e.easing,b,k,g));var A=I(p.opacity,q.opacity,e.easing,b,k,g);e.element.style.transform="translate("+c+"px, "+h+"px)";e.element.style.opacity=A+"";e.i.some(function(B){return void 0===
B.m})||e.element.setTargetYaw(Math.round(I(p.m,q.m,e.easing,b,k,g)))}O("parallaxscrolled",a,{yscroll:b})}function ca(a){var b=J(a,"start",0),d=J(a,"end",1);if(0>b||1<b||0>d||1<d||b>=d)b=0,d=1;a=J(a,"middle",-1);return a>=b&&a<=d?[b,a,d]:[b,d]}l.M=function(){var a=this;setTimeout(function(){a.initializeParallax(!1);R(a,1,window.innerHeight+a.l)},1)};l.L=function(){var a=this;setTimeout(function(){a.initializeParallax(!1);R(a,a.A,window.innerHeight+a.l)},1)};
r.Object.defineProperties(P,{observedAttributes:{configurable:!0,enumerable:!0,get:function(){return ba}}});function Z(){return P.call(this)||this}z(Z,P);customElements.define("gwd-parallax",Z);/*

 SPDX-License-Identifier: Apache-2.0
*/
}).call(this);
