import Wrapper from '@/components/Wrapper';
import './globals.css';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko" className="w-full h-full">
      <body className="w-full h-full">
        <Wrapper>{children}</Wrapper>
      </body>
    </html>
  );
}
